# Generated by Django 3.0.5 on 2020-04-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200408_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='diretors',
            new_name='directors',
        ),
    ]
